# -*- coding: utf-8 -*-
"""milestone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DXX920HdjiS4jOHSsajfGeEnz1Kpjuo6
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report


df = pd.read_csv("attendance_students.csv")

print("\nDataset Loaded Successfully")
print("Dataset Shape:", df.shape)

print("\nChecking Missing Values...")
print(df.isnull().sum())

df.fillna(0, inplace=True)

print("\nChecking Duplicates...")
duplicates = df.duplicated().sum()

print("Duplicate Rows:", duplicates)

df.drop_duplicates(inplace=True)


session_cols = [f"Session_{i}" for i in range(1, 41)]

df["Classes_Attended"] = df[session_cols].sum(axis=1)

df["Attendance_Percentage"] = (
    df["Classes_Attended"] / 40
) * 100


df["Certification"] = np.where(
    df["Attendance_Percentage"] >= 80,
    "Certified",
    "Not Certified"
)


print("\nAttendance Statistics")

print(
    "Average Attendance:",
    round(df["Attendance_Percentage"].mean(), 2)
)

print(
    "Maximum Attendance:",
    round(df["Attendance_Percentage"].max(), 2)
)

print(
    "Minimum Attendance:",
    round(df["Attendance_Percentage"].min(), 2)
)

print("\nCertification Count")

print(df["Certification"].value_counts())


plt.figure(figsize=(10, 5))

sns.histplot(
    df["Attendance_Percentage"],
    bins=20,
    kde=True
)

plt.title("Attendance Distribution")
plt.xlabel("Attendance Percentage")
plt.ylabel("Students")

plt.tight_layout()
plt.show()


plt.figure(figsize=(6, 4))

sns.countplot(
    x="Certification",
    data=df
)

plt.title("Certified vs Not Certified")

plt.tight_layout()
plt.show()


plt.figure(figsize=(7, 7))

df["Certification"].value_counts().plot(
    kind="pie",
    autopct="%1.1f%%"
)

plt.title("Certification Distribution")
plt.ylabel("")

plt.tight_layout()
plt.show()


plt.figure(figsize=(12, 6))

sns.scatterplot(
    x=df.index,
    y="Attendance_Percentage",
    hue="Certification",
    data=df
)

plt.title("Certified vs Uncertified Students")
plt.xlabel("Student Number")
plt.ylabel("Attendance Percentage")

plt.tight_layout()
plt.show()

df["Certification_Label"] = np.where(
    df["Certification"] == "Certified",
    1,
    0
)

X = df[["Attendance_Percentage"]]

y = df["Certification_Label"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

model = LogisticRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(
    y_test,
    y_pred
)

print(
    "\nModel Accuracy:",
    round(accuracy * 100, 2),
    "%"
)

print("\nClassification Report")

print(
    classification_report(
        y_test,
        y_pred
    )
)

attendance = float(
    input(
        "\nEnter Attendance Percentage: "
    )
)

prediction = model.predict(
    pd.DataFrame(
        [[attendance]],
        columns=["Attendance_Percentage"]
    )
)

if prediction[0] == 1:
    print("Student is CERTIFIED")
else:
    print("Student is NOT CERTIFIED")
report = df[
    [
        "Student_ID",
        "Student_Name",
        "Classes_Attended",
        "Attendance_Percentage",
        "Certification"
    ]
]

report.to_csv(
    "Attendance_Report.csv",
    index=False
)

print("\nFinal Report Generated Successfully")
print("Saved as: Attendance_Report.csv")

